### PR TITLE
Volley updates from ION-Volley migration

### PR DESCRIPTION
**Pull request by mflores13**
CC @shanem @brandonchinn 

- [x] has been CR'ed by @shanem or @brandonchinn

### CODE REVIEW

**Comment by mflores13** [comment]
@shanem @brandonchinn 
I created this as a public fork and this was the only change that made the most sense to move here.  I could make this a private fork and move some of our InputStream logic to here if we want to separate it out more, but that's mostly logic needed due to our usage from ION.

**Comment by shanem** [comment]
:+1:

**Comment by damien5314** [comment]
@mflores13 Question- do you remember why we needed this change? I would like to remove the submodule from Android project and start importing Volley via a gradle dependency if possible, for ease of updating, but I want to make sure I account for the reason we needed a fork in the first place.

**Comment by mflores13** [comment]
@damien5314 Do you mean why the change represented by this PR is needed?  Volley did (doesn't?) support providing data in the body of the request however is allowed through our API, and is used by the App.  If we submit this change to upstream volley, or change our own implementations to not use data in the body with our DELETE calls, then you would be able to move forward to just use the upstream volley.

**Pull request merged**
